// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idczmbtffmcorjyamdss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY3ptYnRmZm1jb3JqeWFtZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjczMTksImV4cCI6MjA2NjI0MzMxOX0.lMv5Y8HkE0xEPxqDdCeA5E8zm4-R5nVInzf_ik4e2Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);